language: java
jdk:
    - oraclejdk7

script: mvn install

install:
    - wget https://s3-us-west-2.amazonaws.com/imhotep-build/imhotep.pom
    - mvn install:install-file -Dfile=imhotep.pom -DgroupId=com.indeed -DartifactId=imhotep -Dversion=1.0.10-SNAPSHOT -Dpackaging=xml -DpomFile=imhotep.pom
    - IMHOTEP_SERVER_JAR=`curl -s https://s3-us-west-2.amazonaws.com/imhotep-build/ | egrep -o "imhotep-server-[0-9\.]+-SNAPSHOT.jar" | head -1`
    - wget https://s3-us-west-2.amazonaws.com/imhotep-build/$IMHOTEP_SERVER_JAR
    - wget https://s3-us-west-2.amazonaws.com/imhotep-build/imhotep-server.pom
    - mvn install:install-file -Dfile=imhotep-server-1.0.10-SNAPSHOT.jar -DgroupId=com.indeed -DartifactId=imhotep-server -Dversion=1.0.10-SNAPSHOT -Dpackaging=jar -DpomFile=imhotep-server.pom
    - IMHOTEP_CLIENT_JAR=`curl -s https://s3-us-west-2.amazonaws.com/imhotep-build/ | egrep -o "imhotep-client-[0-9\.]+-SNAPSHOT.jar" | head -1`
    - wget https://s3-us-west-2.amazonaws.com/imhotep-build/$IMHOTEP_CLIENT_JAR
    - wget https://s3-us-west-2.amazonaws.com/imhotep-build/imhotep-client.pom
    - mvn install:install-file -Dfile=imhotep-client-1.0.10-SNAPSHOT.jar -DgroupId=com.indeed -DartifactId=imhotep-client -Dversion=1.0.10-SNAPSHOT -Dpackaging=jar -DpomFile=imhotep-client.pom
    - IMHOTEP_ARCHIVE_JAR=`curl -s https://s3-us-west-2.amazonaws.com/imhotep-build/ | egrep -o "imhotep-archive-[0-9\.]+-SNAPSHOT.jar" | head -1`
    - wget https://s3-us-west-2.amazonaws.com/imhotep-build/$IMHOTEP_ARCHIVE_JAR
    - wget https://s3-us-west-2.amazonaws.com/imhotep-build/imhotep-archive.pom
    - mvn install:install-file -Dfile=imhotep-archive-1.0.10-SNAPSHOT.jar -DgroupId=com.indeed -DartifactId=imhotep-archive -Dversion=1.0.10-SNAPSHOT -Dpackaging=jar -DpomFile=imhotep-archive.pom

before_deploy:
    - mkdir deploy
    - cp */target/*builder*.* deploy/
    - cp pom.xml deploy/imhotep-tsv-converter.pom
    - cp index-builder-util/pom.xml deploy/index-builder-util.pom
    - cp tsv-converter/pom.xml deploy/tsv-converter.pom

deploy:
    provider: s3
    access_key_id: AKIAJVZNZT5TTB2Y4BNA
    secret_access_key:
      secure: FLV4Zf11wjfEIMgVjiIvx8Q0IUZqxLspcwAZRu9tROby79vs8mKC/eEfgq+VIGKaLTL+U6bA6i9Dp6NJ4r+8JLCNRez4AEYHbTPDnJ+m6FcvVuBSamDHN1bEey1PTkhXsJ3hTBrBA4msZ7VFkfiiqYuyGbMcwGazEq3UcH
evo0M=
    bucket: indeedeng-imhotep-build
    local-dir: deploy
    skip_cleanup: true
    region: us-west-2
