language: java
jdk:
    - oraclejdk7

script: mvn install

install:
    - IMHOTEP_SERVER_JAR=`curl -s https://s3-us-west-2.amazonaws.com/imhotep-build/ | egrep -o "imhotep-server-[0-9\.]+-SNAPSHOT.jar" | head -1`
    - wget https://s3-us-west-2.amazonaws.com/imhotep-build/$IMHOTEP_SERVER_JAR
    - mvn install:install-file -Dfile=imhotep-server-1.0.10-SNAPSHOT.jar -DgroupId=com.indeed -DartifactId=imhotep-server -Dversion=1.0.10-SNAPSHOT -Dpackaging=jar
    - IMHOTEP_CLIENT_JAR=`curl -s https://s3-us-west-2.amazonaws.com/imhotep-build/ | egrep -o "imhotep-client-[0-9\.]+-SNAPSHOT.jar" | head -1`
    - wget https://s3-us-west-2.amazonaws.com/imhotep-build/$IMHOTEP_CLIENT_JAR
    - mvn install:install-file -Dfile=imhotep-client-1.0.10-SNAPSHOT.jar -DgroupId=com.indeed -DartifactId=imhotep-client -Dversion=1.0.10-SNAPSHOT -Dpackaging=jar
    - IMHOTEP_ARCHIVE_JAR=`curl -s https://s3-us-west-2.amazonaws.com/imhotep-build/ | egrep -o "imhotep-archive-[0-9\.]+-SNAPSHOT.jar" | head -1`
    - wget https://s3-us-west-2.amazonaws.com/imhotep-build/$IMHOTEP_ARCHIVE_JAR
    - mvn install:install-file -Dfile=imhotep-archive-1.0.10-SNAPSHOT.jar -DgroupId=com.indeed -DartifactId=imhotep-archive -Dversion=1.0.10-SNAPSHOT -Dpackaging=jar

before_deploy:
    - mkdir deploy
    - cp */target/*builder*.* deploy/

deploy:
    provider: s3
    access_key_id: AKIAID3AAXWWTV2KQYEA
    secret_access_key:
      secure: Q/sL14YsB/ouKeY2vHJaYb6QUV4ZBTtBH1VY9e9T2SBqn2n+m/SeII/Z6PwQuPwSE4L+LdpmXrVydRimRHf2PI9NxDqeZPjqXNWSxK+/S/2Y+lJ2ikOnOEfvOOfvxKwjlsKm6sXrWwbczARJhwepnJj7nXs1W0S4amysmPpWIIc=
    bucket: imhotep-build
    local-dir: deploy
    skip_cleanup: true
    region: us-west-2
